config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'
  resources :users do
    member do
      put 'like' => 'users#upvote'
      put 'unlike' => 'users#downvote'
    end
    resources :trades, except: :update
    resources :trade_items
    resources :items
  end
  resources :locations
  resources :trades, only: :update

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :items
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :validatable, :rememberable

  acts_as_votable
  acts_as_voter

  has_one_attached :avatar

  has_many :items, inverse_of: :user, dependent: :delete_all

  scope :infected, -> { where(infected: 1).count.to_f }
  scope :not_infected, -> { where(infected: 0).count.to_f }
  scope :all_users_accept_current, ->(user_id) { where.not(id: user_id) }

  enum gender: { female: 1, male: 2, other: 3 }

  accepts_nested_attributes_for :items, allow_destroy: true, reject_if: :all_blank

  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def with_item
    items.new if items.blank?
    self
  end

  def infected_percentage
    percentage(User.infected / User.all.count.to_f)
  end

  def non_infected_percentage
    percentage(User.not_infected / User.all.count.to_f)
  end

  def average_resources_values
    Item.group(:item_name).count.values.map! { |n| (n / User.all.count.to_f).round(3) }
  end

  def average_resources_keys
    Item.group(:item_name).count.keys
  end

  def points
    Item.where(user_id: User.where(infected: 1)).map(&:points).inject(:+)
  end

  def percentage(number)
    number.round(4) * 100
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class UsersController < ApplicationController
      def index
        users = User.all

        render json: users
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!

  def upvote
    authorize current_user
    @user.upvote_from current_user if @user.get_upvotes.size < FLAG_LIMIT
    if @user.get_upvotes.size == FLAG_LIMIT
      @user.infected = true
      @user.save
      flash[:alert] = "flag couldn't be save" unless @user.save
    end
    redirect_to root_path
  end

  def show
    authorize @user
    @items = @user.items
  end

  def downvote
    @user.downvote_from current_user unless @user.infected
    authorize current_user
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find_by(id: user_params[:id])
    raise ActiveRecord::RecordNotFound if @user.nil?
  end

  def user_params
    params.permit(:id)
  end
end

app/views/users/_user.html.erb
<% if !user.infected? %>
  <div class="card" style="width: 18rem;">
    <% if user.avatar_attachment.present? %>
      <%= image_tag( user.avatar ,class: "card-img-top") %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= user.name %></h5>
      <h6 class="card-title">
        <% if user.location_history %>
          <%=location_array(user.location_history).last['longitude']%>
          <%=location_array(user.location_history).last['latitude']%>
        <% end %>
      </h6>
      <% if !current_user.infected? %>
        <% if !current_user.voted_up_on? user %>
          <%= link_to like_user_path(user), class: "like",method: :put do %>
            <button type="button" class ="btn btn-info" arial-label ="Left Align">
              <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center " aria-hidden="true">
              </span>
              <span class="badge">
                Flag
              </span>
            </button>
          <% end %>
        <% else %>
          <%= link_to unlike_user_path(user), class: "like",method: :put do %>
            <button type="button" class ="btn btn-info" arial-label ="Left Align">
              <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center " aria-hidden="true">
              </span>
              <span class="badge">
                Unflag
              </span>
            </button>
          <% end %>
        <% end %>
        <%= link_to "Inventory", user_items_path(user) %>
      <% end %>
    </div>
  <% end %>
</div>