config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'
  resources :users do
    member do
      put 'like' => 'users#upvote'
      put 'unlike' => 'users#downvote'
    end
    resources :trades, except: :update
    resources :trade_items
    resources :items
  end
  resources :locations
  resources :trades, only: :update

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :items
      end
    end
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :user, optional: true

  has_many :trade_items, dependent: :delete_all
  has_many :trades, through: :trade_items

  validates :points, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, presence: true
  validates :item_name, presence: true
end

app/controllers/api/v1/items_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ItemsController < ApplicationController
      before_action :set_user, only: :index
      def index
        items = @user.items
        render json: items
      end

      private

      def set_user
        @user = User.find_by(id: params[:user_id])
      end
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_user, only: :index
  def index
    @items = @user.items
    authorize @items
  end

  private

  def set_user
    @user = User.find_by(id: params[:user_id])
    authorize :item, :access?
    raise ActiveRecord::RecordNotFound if @user.nil?
  end
end

app/views/items/_item.html.erb
<tbody>
  <tr scope="row">
    <td> <%= item.item_name %> </td>
    <td> <%= item.points %> </td>
  </tr>
  <tr class="spacer">
    <td colspan="100"></td>
  </tr>
</tbody>

app/views/items/index.html.erb
<div class="content">
  <div class="container">
    <h2 class="mb-5 text-center">Inventory</h2>
    <div class="table-responsive custom-table-responsive">
      <table class="table custom-table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Points</th>
          </tr>
        </thead>
        <%= render @items %>
      </table>
    </div>
  </div>
</div>
<% if !@user.eql?(current_user) %>
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <%= link_to "Trade",new_user_trade_path(@user), :class => "btn btn-secondary  "  %>
      </div>
    </div>
  </div>
<% end %>