config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'
  resources :users do
    member do
      put 'like' => 'users#upvote'
      put 'unlike' => 'users#downvote'
    end
    resources :trades, except: :update
    resources :trade_items
    resources :items
  end
  resources :locations
  resources :trades, only: :update

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :items
      end
    end
  end
end

app/models/trade.rb
# frozen_string_literal: true

class Trade < ApplicationRecord
  belongs_to :receiver, class_name: :User
  belongs_to :sender, class_name: :User

  has_many :trade_items, dependent: :delete_all
  has_many :items, through: :trade_items

  accepts_nested_attributes_for :trade_items, allow_destroy: true, reject_if: :all_blank

  scope :sender_receiver_trades, ->(user_id) { where('sender_id = ? OR receiver_id = ?', user_id, user_id) }

  enum status: { pending: 1, rejected: 2, cancelled: 3, accepted: 4 }

  def accept
    items.each do |item|
      item.user_id == receiver_id ? item.update(user_id: sender_id) : item.update(user_id: receiver_id)
    end
    accepted!
  end
end

app/controllers/trades_controller.rb
# frozen_string_literal: true

class TradesController < ApplicationController
  include Trader

  before_action :set_user, :trade_params, except: :update
  before_action :set_trade, only: :update
  def index
    @trades = Trade.sender_receiver_trades(current_user.id)
    authorize @trades
  end

  def new
    @sender_items = read_sender_items(current_user)
    @receiver_items = read_receiver_items
    @trade = Trade.new(receiver_id: @user.id, sender_id: current_user.id)
    authorize @trade
  end

  def update
    authorize @trade
    @trade.status = params[:status].to_i
    @trade.accept if @trade.accepted?
    if @trade.save
      redirect_to user_trades_path(current_user)
    else
      flash[:alert] = "Trade couldn't be save"
    end
  end

  def create
    authorize :trade
    trade_items = trade_initializer

    return unless trade_items

    @trade = create_trade(trade_items)
    redirect_to user_trades_path(current_user)
  end

  def create_trade(trade_items)
    Trade.new.tap do |t|
      t.receiver_id = trade_create_params[:receiver_id]
      t.sender_id =  trade_create_params[:sender_id]
      t.trade_items_attributes = trade_items.to_h
      t.save
    end
  end

  def set_user
    @user = User.find_by(id: params[:user_id])
    raise ActiveRecord::RecordNotFound if @user.nil?
  end

  def set_trade
    @trade = Trade.find_by(id: params[:id])
    raise ActiveRecord::RecordNotFound if @trade.nil?

    authorize @trade
  end

  def trade_params
    params.permit(:id, :user_id)
  end

  def trade_create_params
    params.require(:trade).permit(:id, :sender_id, :receiver_id,
                                  sender_items: %i[item_id quantity],
                                  receiver_items: %i[item_id quantity])
  end

  private

  def read_sender_items(current_user)
    @sender_items = current_user.items
  end

  def read_receiver_items
    @receiver_items = @user.items
  end
end

app/views/trades/_form.html.erb
<%= nested_form_for([@user, @trade]) do |f| %>
  <div class="row">
    <div class="  col ">
      <table>
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">item</th>
            <th scope="col">points</th>
            <th scope="col">quantity</th>
          </tr>
        </thead>
        <tbody>
          <% @sender_items.each do |item| %>
            <tr>
              <%= f.fields_for :sender_items, nil, index: item.id  do |f| %>
                <td> <%= f.check_box :item_id, { checked: false }, item.id, nil  %> </td>
                <td> <%= item.item_name %> </td>
                <td> <%= item.points %> </td>
                <td> <%= f.text_field :quantity %> </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col">
      <table>
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">item</th>
            <th scope="col">points</th>
            <th scope="col">quantity</th>
          </tr>
        </thead>
        <tbody>
          <% @receiver_items.each do |item| %>
            <tr>
              <%= f.fields_for :receiver_items, nil, index: item.id  do |f| %>
                <td> <%= f.check_box :item_id, { checked: false }, item.id, nil  %> </td>
                <td> <%= item.item_name %> </td>
                <td> <%= item.points %> </td>
                <td> <%= f.number_field :quantity %> </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= f.hidden_field  :receiver_id%>
  <%= f.hidden_field  :sender_id%>
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <div class="actions  ">
          <%= f.submit "Proceed" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/trades/_trade.html.erb
<tbody>
  <tr scope="row">
    <td> <%= trade.sender.name %> </td>
    <td> <%= trade.receiver.name%> </td>
    <td> <%= trade.status%> </td>
    <td><%= render trade.trade_items%></td>
    <td>
      <% if sender?(trade, current_user) %>
        <% if trade.pending? %>
          <div class="container">
            <div class="row">
              <div class="col text-center">
                <%= link_to "Cancel" , trade_path(trade, status: 3), method: :patch, :class => "btn btn-secondary  "  %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <% if check_status(trade)%>
          <div class="container">
            <div class="row">
              <div class="col text-center">
                <%= link_to "Reject",trade_path(trade, status: 2), method: :patch, :class => "btn btn-secondary  "  %>
              </div>
            </div>
          </div>
          <div class="container">
            <div class="row">
              <div class="col text-center">
                <%= link_to "Accept", trade_path(trade, status: 4), method: :patch, :class => "btn btn-secondary  "  %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </td>
  </tr>
  <tr class="spacer">
    <td colspan="100"></td>
  </tr>
</tbody>

app/views/trades/index.html.erb
<div class="content">
  <div class="container">
    <h2 class="mb-5 text-center">Inventory</h2>
    <div class="table-responsive custom-table-responsive">
      <table class="table custom-table">
        <thead>
          <tr>
            <th scope="col">Reciever</th>
            <th scope="col">Sender</th>
            <th scope="col">Status</th>
            <th scope="col">items </th>
          </tr>
        </thead>
        <%= render @trades %>
      </table>
    </div>
  </div>
</div>

app/views/trades/new.html.erb
<h1>Trade </h1>
<%= render "form" %>