config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'
  resources :users do
    member do
      put 'like' => 'users#upvote'
      put 'unlike' => 'users#downvote'
    end
    resources :trades, except: :update
    resources :trade_items
    resources :items
  end
  resources :locations
  resources :trades, only: :update

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :items
      end
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Zombie Apocalypse Survival</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Locations", locations_path, class: "nav-link"  %>
        </li>
        <% if  !current_user.infected?%>
          <li class="nav-item">
            <%= link_to "Items", user_items_path(current_user), class: "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Trade History", user_trades_path(current_user), class: "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Settings", edit_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <% if current_user.avatar_attachment.present? %>
            <%= image_tag(current_user.avatar ,class: "rounded-circle avatar") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZombieApocalypseSurvival</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if current_user and !current_user.admin?%>
      <%= render "layouts/navbar" %>
      <% flash.each do |type, msg| %>
        <div class="alert alert-info">
          <%= msg %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>